# Generated by Django 2.0.5 on 2019-01-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='users.Role', verbose_name='角色'),
        ),
    ]
